version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=localhost
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - nginx-network      
  api:
    build:
      context: './Todo.Api'
      dockerfile: Dockerfile
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge
